{% set python_min = "3.10.0" %}
{% set name = "crunchflow" %}
{% set version = "2.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/crunchflow-{{ version }}.tar.gz
  sha256: 310b4c0c64595d42ba575f3e29e6483139d87e2dd342e8ac8bd2aed5e66cf4fc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - uv-build >=0.9.25,<0.10.0
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - numpy >=2.0.0,<3.0.0
    - matplotlib-base >=3.7.0,<4.0.0
    - pandas >=2.2.2,<3.0.0
    - notebook >=7.5.3,<8

test:
  imports:
    - crunchflow
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/crunchflow/
  summary: A Python toolbox for working with the CrunchFlow reactive transport code
  license: LGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - zperzan
